// <auto-generated />
using System;
using ContentOS.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContentOS.Infrastructure.Migrations
{
    [DbContext(typeof(ContentOsDbContext))]
    partial class ContentOsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ContentOS.Domain.Entities.AgentExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentWorkflowJobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentWorkflowTaskId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AgentExecutionLogs");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CallToAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ArticleChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("ThreadId", "CreatedAtUtc");

                    b.ToTable("ArticleChatMessages");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ArticleChatThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleChatThreads");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ArticleEditPatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FieldLocksRespected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestId", "SortOrder");

                    b.ToTable("ArticleEditPatches");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ArticleEditRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AppliedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiffSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedFields")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposalJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedCallToAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedMetaDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QaStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QaSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoutedAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetSectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.HasIndex("ArticleId", "CreatedAtUtc");

                    b.ToTable("ArticleEditRequests");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ArticleRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CallToAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiffSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("ArticleRevisions");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ArticleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleVersions");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ContentArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentWorkflowJobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentWorkflowTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ContentArtifacts");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ContentIdea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudienceGoal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudiencePainPoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ClickPotentialScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CompetitionModifier")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CompetitionScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Evergreen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FunnelStage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IntentMatchScore")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHighCompetition")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LowCompetitionBoost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonetizationFitScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonetizationPotentialScore")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MonetizationViable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonetizationWarning")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OverallScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryKeyword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedAngle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RejectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchIntent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Seasonal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondaryKeywordsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SeoOpportunityScore")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlugSuggestion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSummaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecificityTag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TrendScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UniquenessScore")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhyNow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("ContentIdeas");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ContentResearchSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentIdeaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContentResearchSources");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ContentWorkflowJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentIdeaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowTemplateVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentIdeaId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("ContentWorkflowJobs");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ContentWorkflowTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentWorkflowJobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionAttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InsertedAfterTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatchPayload")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScopeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScopeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SupersedesTaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkflowTaskTemplateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("ContentWorkflowJobId", "DisplayOrder");

                    b.ToTable("ContentWorkflowTasks");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.IdeaRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudienceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Difficulty")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmotionalTrigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdeaSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdeaTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonetizationFit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriorityScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReaderProblem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RejectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchIntent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SeoPotential")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceWorkflowDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceWorkflowRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniquenessAngle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("SourceWorkflowDefinitionId");

                    b.HasIndex("SourceWorkflowRunId");

                    b.HasIndex("Status", "PriorityScore");

                    b.ToTable("IdeaRecords");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.PublishRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationChannel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("PublishRecord");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Niche")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ArticleIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workflow");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowActionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkflowTemplateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowTemplateId");

                    b.HasIndex("WorkflowDefinitionId", "Order")
                        .IsUnique();

                    b.ToTable("WorkflowActionDefinitions");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowActionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFailureUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputSnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowActionDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowDefinitionRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowActionDefinitionId");

                    b.HasIndex("WorkflowDefinitionRunId", "Order");

                    b.HasIndex("WorkflowDefinitionRunId", "WorkflowActionDefinitionId")
                        .IsUnique();

                    b.ToTable("WorkflowActionRuns");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowDefinitionFamilyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionFamilyId", "IsActive");

                    b.HasIndex("WorkflowDefinitionFamilyId", "Version")
                        .IsUnique();

                    b.ToTable("WorkflowDefinitions");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowDefinitionFamily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveWorkflowDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name", "WorkflowType")
                        .IsUnique();

                    b.ToTable("WorkflowDefinitionFamilies");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowDefinitionMutation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MutationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId", "CreatedUtc");

                    b.ToTable("WorkflowDefinitionMutations");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowDefinitionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IdeaRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowDefinitionFamilyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdeaRecordId");

                    b.HasIndex("WorkflowDefinitionFamilyId");

                    b.HasIndex("WorkflowDefinitionId", "StartedUtc");

                    b.HasIndex("WorkflowType", "Status");

                    b.ToTable("WorkflowDefinitionRuns");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowMutationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentWorkflowJobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContentWorkflowTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MutationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentWorkflowJobId", "CreatedUtc");

                    b.ToTable("WorkflowMutationLogs");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowRun");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowStepDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowActionDefinitionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowActionDefinitionId", "Order")
                        .IsUnique();

                    b.ToTable("WorkflowStepDefinitions");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowStepRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputSnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowActionRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowStepDefinitionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowStepDefinitionId");

                    b.HasIndex("WorkflowActionRunId", "Order");

                    b.HasIndex("WorkflowActionRunId", "WorkflowStepDefinitionId")
                        .IsUnique();

                    b.ToTable("WorkflowStepRuns");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowTaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStartWhenPreviousComplete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedOutputsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructionsTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApprovalRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredInputsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowTemplateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowTemplateId", "DisplayOrder");

                    b.ToTable("WorkflowTaskTemplates");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WorkflowTemplates");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowTemplateTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultInstructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowTemplateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowTemplateId");

                    b.ToTable("WorkflowTemplateTask");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ArticleChatMessage", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.ArticleEditRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.HasOne("ContentOS.Domain.Entities.ArticleChatThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ArticleChatThread", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.Article", null)
                        .WithMany("ChatThreads")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ArticleEditPatch", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.ArticleEditRequest", "Request")
                        .WithMany("Patches")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ArticleEditRequest", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.ArticleChatThread", "Thread")
                        .WithMany("EditRequests")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ArticleRevision", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.Article", null)
                        .WithMany("Revisions")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ArticleVersion", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.Article", "Article")
                        .WithMany("Versions")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ContentWorkflowTask", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.ContentWorkflowJob", null)
                        .WithMany()
                        .HasForeignKey("ContentWorkflowJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.IdeaRecord", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.WorkflowDefinition", null)
                        .WithMany()
                        .HasForeignKey("SourceWorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContentOS.Domain.Entities.WorkflowDefinitionRun", null)
                        .WithMany()
                        .HasForeignKey("SourceWorkflowRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.PublishRecord", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.Article", "Article")
                        .WithMany("PublishHistory")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowActionDefinition", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.WorkflowDefinition", null)
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentOS.Domain.Entities.WorkflowTemplate", null)
                        .WithMany("Actions")
                        .HasForeignKey("WorkflowTemplateId");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowActionRun", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.WorkflowActionDefinition", null)
                        .WithMany()
                        .HasForeignKey("WorkflowActionDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContentOS.Domain.Entities.WorkflowDefinitionRun", null)
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.WorkflowDefinitionFamily", null)
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowDefinitionRun", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.IdeaRecord", null)
                        .WithMany()
                        .HasForeignKey("IdeaRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ContentOS.Domain.Entities.WorkflowDefinitionFamily", null)
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionFamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContentOS.Domain.Entities.WorkflowDefinition", null)
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowRun", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.Article", null)
                        .WithMany("WorkflowRuns")
                        .HasForeignKey("ArticleId");

                    b.HasOne("ContentOS.Domain.Entities.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowStepDefinition", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.WorkflowActionDefinition", null)
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowActionDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowStepRun", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.WorkflowActionRun", null)
                        .WithMany()
                        .HasForeignKey("WorkflowActionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentOS.Domain.Entities.WorkflowStepDefinition", null)
                        .WithMany()
                        .HasForeignKey("WorkflowStepDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowTemplateTask", b =>
                {
                    b.HasOne("ContentOS.Domain.Entities.WorkflowTemplate", null)
                        .WithMany("Tasks")
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.Article", b =>
                {
                    b.Navigation("ChatThreads");

                    b.Navigation("PublishHistory");

                    b.Navigation("Revisions");

                    b.Navigation("Versions");

                    b.Navigation("WorkflowRuns");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ArticleChatThread", b =>
                {
                    b.Navigation("EditRequests");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.ArticleEditRequest", b =>
                {
                    b.Navigation("Patches");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowActionDefinition", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ContentOS.Domain.Entities.WorkflowTemplate", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
